---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - export PATH=/usr/local/phantomjs-2.0/bin:$PATH
  - phantomjs -v
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
